export const Clanker_v0_abi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'owner_', type: 'address', internalType: 'address' },
      { name: 'teamSpender_', type: 'address', internalType: 'address' },
      { name: 'teamGrantedTokens_', type: 'address[]', internalType: 'address[]' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initializeTokenCreator',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'newCreator', type: 'address', internalType: 'address' },
      { name: 'proof', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setTeamSpender',
    inputs: [{ name: 'teamSpender_', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setTokenCreatorRoot',
    inputs: [{ name: 'tokenCreatorRoot_', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'teamGrantedTokens',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'teamGrantedTokensMap',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'teamGranted', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'teamSpender',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'teamTransfer',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'teamTransferEth',
    inputs: [{ name: 'safe', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tokenCreator',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'creator', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenCreatorRoot',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenCreatorTransfer',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateTokenCreator',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'newCreator', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'InitializeTokenCreator',
    inputs: [
      { name: 'token', type: 'address', indexed: false, internalType: 'address' },
      { name: 'initializer', type: 'address', indexed: false, internalType: 'address' },
      { name: 'creator', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetTeamSpender',
    inputs: [
      { name: 'previousTeamSpender', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newTeamSpender', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetTokenCreatorRoot',
    inputs: [
      { name: 'tokenCreatorRoot', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'safe', type: 'address', indexed: true, internalType: 'address' },
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'spender', type: 'address', indexed: false, internalType: 'address' },
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'UpdateTokenCreator',
    inputs: [
      { name: 'token', type: 'address', indexed: false, internalType: 'address' },
      { name: 'previousCreator', type: 'address', indexed: false, internalType: 'address' },
      { name: 'newCreator', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'InsufficientBalance',
    inputs: [
      { name: 'safe', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'balance', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { type: 'error', name: 'InvalidProof', inputs: [] },
  {
    type: 'error',
    name: 'NotAuthorizedToSpend',
    inputs: [
      { name: 'sender', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'TokenCreatorAlreadyInitialized',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'delegate', type: 'address', internalType: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'TokenCreatorRootAlreadySet',
    inputs: [{ name: 'tokenCreatorRoot', type: 'bytes32', internalType: 'bytes32' }],
  },
  { type: 'error', name: 'TokenCreatorRootNotSet', inputs: [] },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [{ name: 'unauthorized', type: 'address', internalType: 'address' }],
  },
] as const;
